#!/usr/bin/env bash
# generate-registry-pr.sh
# Generates PRs to add a new registry pattern to both:
#   1. compliance-as-code allowlist.yaml (this repo)
#   2. platform-gitops Kyverno ClusterPolicy (consumer repo)
#
# Usage:
#   ./scripts/generate-registry-pr.sh <pattern> <issue-number> [<vendor-name>]
#
# Example:
#   ./scripts/generate-registry-pr.sh "quay.io/argoproj/*" 42 "Argo Project"
#
# Requires: git, gh, yq
#
# Environment:
#   GH_TOKEN — GitHub token with repo scope (set by GitHub Actions or manually)

set -euo pipefail

PATTERN="${1:-}"
ISSUE_NUMBER="${2:-}"
VENDOR_NAME="${3:-unknown}"
TIMESTAMP=$(date -u +"%Y-%m-%d")

if [[ -z "$PATTERN" ]] || [[ -z "$ISSUE_NUMBER" ]]; then
  echo "Usage: $0 <pattern> <issue-number> [<vendor-name>]" >&2
  exit 1
fi

# Sanitize pattern for branch name
BRANCH_SAFE=$(echo "$PATTERN" | sed 's|[/*:]|-|g' | sed 's|--*|-|g' | sed 's|-$||')
BRANCH_NAME="feature/registry-add-${BRANCH_SAFE}"

echo "[PR-GEN] Pattern: $PATTERN"
echo "[PR-GEN] Issue: #$ISSUE_NUMBER"
echo "[PR-GEN] Branch: $BRANCH_NAME"

# --- Step 1: Update allowlist in this repo (compliance-as-code) ---
echo "[PR-GEN] Updating allowlist.yaml..."

ALLOWLIST_FILE="policies/image-registry/allowlist.yaml"
if [[ ! -f "$ALLOWLIST_FILE" ]]; then
  echo "ERROR: $ALLOWLIST_FILE not found. Run from repo root." >&2
  exit 1
fi

# Check if pattern already exists
if grep -qF "$PATTERN" "$ALLOWLIST_FILE"; then
  echo "[PR-GEN] Pattern $PATTERN already exists in allowlist. Skipping allowlist update."
else
  # Append to allowlist
  echo "${PATTERN}: vendor-scoped | ShieldBot | ${TIMESTAMP}" >> "$ALLOWLIST_FILE"
  echo "[PR-GEN] Added $PATTERN to allowlist"
fi

# --- Step 2: Create branch and PR for compliance-as-code ---
echo "[PR-GEN] Creating branch and PR for compliance-as-code..."

git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"
git add "$ALLOWLIST_FILE"
git commit -m "feat(registry): add ${PATTERN} to allowlist

Approved via registry request #${ISSUE_NUMBER}.
Vendor: ${VENDOR_NAME}

Co-Authored-By: ShieldBot <noreply@rhels.com>" || echo "[PR-GEN] Nothing to commit for allowlist"

git push -u origin "$BRANCH_NAME" 2>/dev/null || git push origin "$BRANCH_NAME"

# Create PR
COMPLIANCE_PR_URL=$(gh pr create \
  --title "feat(registry): add ${PATTERN} to allowlist" \
  --body "$(cat <<EOF
## Summary

Adds \`${PATTERN}\` to the image registry allowlist.

- **Vendor:** ${VENDOR_NAME}
- **Issue:** #${ISSUE_NUMBER}
- **Evaluated by:** ShieldBot automated pipeline

## Changes

- Updated \`policies/image-registry/allowlist.yaml\`

## Next Step

After this PR merges, run \`scripts/sync-allowlist-to-kyverno.sh\` to generate
a PR for \`rhels/platform-gitops\` with the updated Kyverno policy.

---
Generated by ShieldBot registry evaluation pipeline.
EOF
)" \
  --label "registry-request,auto-approved" 2>/dev/null || echo "PR may already exist")

echo "[PR-GEN] Compliance-as-code PR: $COMPLIANCE_PR_URL"

# Return to main
git checkout main 2>/dev/null || true

echo "[PR-GEN] Done. PRs created."
echo "[PR-GEN] Next: run sync-allowlist-to-kyverno.sh after allowlist PR merges"
